# Generated by Django 4.2.13 on 2024-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pdffile',
            name='direction',
            field=models.CharField(default='common', max_length=100),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='authors',
            field=models.ManyToManyField(to='catalog.author'),
        ),
    ]
