# Generated by Django 4.2.13 on 2024-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_institute_author_middle_name_author_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='author',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='position',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
