# Generated by Django 4.2.13 on 2024-05-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
