# Generated by Django 4.2.13 on 2024-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, related_name='author_set', to='catalog.pdffile'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='pdf_file_set', to='catalog.author'),
        ),
    ]
